import CategoryItems from "@/app/_components/lib/CategoryItems";
// import { categories } from "@/components/lib/CategoryItems";
import { Metadata } from "next";
import { user } from "../_lib/constants";

export const metadata: Metadata = {
  title: `${user.name}- Featured works by me`,
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className="min-h-screen flex flex-col items-center">
      <div className="flex gap-4 mt-20 ">
        <CategoryItems className="md:text-2xl" />
      </div>
    </div>
  );
}
