import OpacityTransition from "../_components/transition/OpacityTransition";
import Header from "../_components/layout/Header";
import { user } from "../_lib/constants";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: `${user.website} - About`,
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <OpacityTransition>
      <div className="flex h-auto justify-center items-center w-full relative flex-col"></div>
    </OpacityTransition>
  );
}
