import type { Metadata } from "next";
import "./globals.css";
import StateProvider from "@/provider/StateProvider";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import { user } from "@/lib/constants";
import { geistMono, geistSans } from "@/components/ui/fonts/fonts";
import Container from "@/components/layout/Container";

export const metadata: Metadata = {
  title: `${user.name}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StateProvider>
          <main className="flex flex-grow flex-col justify-center items-center w-screen">
            <Header />
            <Navbar />
            {children}
            <Container classNames="justify-center items-center bg-black w-full relative">
              <Footer />
            </Container>
          </main>
        </StateProvider>
      </body>
    </html>
  );
}
