import React from "react";
import OpacityTransition from "@/app/_components/transition/OpacityTransition";
import ScrollYGallery from "@/app/_components/ui/ScrollYGallery";
import { Metadata } from "next";
import { user } from "@/app/_lib/constants";
import data from "@/app/_components/ui/definitons/data";

export const metadata: Metadata = {
  title: `${user.name}- Featured works by me`,
  description: "Generated by create next app",
};

const Features = async ({ params }: { params: { id: number  } }) => {
    const propsId = params.id;


  return (
    <OpacityTransition>
      <div className="min-h-screen h-auto flex justify-center items-center flex-col w-full relative">
        <ScrollYGallery data={data} id={propsId} />
      </div>
    </OpacityTransition>
  );
};

export default Features;
